Repository ZeroOctave/ZeroOctave-Javascript-Projects, pull requests merged in 2022-09, with the labels that each got.

#876 added humidity and windspeed
  assets/Js/weather_app.js
  assets/css/weather_app.css
Labels: review-done, SSOC, Intermediate

#861 updated Password Validator
  Public/confirmpasswordvalidator.html
  assets/Images/Paaword page.png
  assets/Images/Paaword-4.jpg
  assets/Js/confirmpasswordvalidator.js
  assets/css/bmi-calculator.css
  assets/css/confirmpassword.css
Labels: SSOC, Advance

#873 Update style.css
  style.css
Labels: review-done, SSOC, Intermediate

#883 modified tip calculator with tailwind css
  Public/tip_calculator.html
  assets/css/tip_calculator.css
Labels: enhancement, SSOC, Intermediate

#885 Improved UI of Temperature Converter
  Public/temperature-converter.html
  assets/Images/seasons.jpg
  assets/Js/temperature-converter.js
Labels: SSOC, Intermediate

#882 Happy Hacktober site Updated
  Public/happy_hacktober/happyhactober.html
  Public/happy_hacktober/message.html
  assets/Images/Happy-Hacktober.png
  assets/Images/hacktober.png
  assets/Images/hacktoberfest.png
  assets/css/happy_hacktober/happyhacktober.css
  assets/css/happy_hacktober/message.css
Labels: SSOC, Intermediate

#841 Changed color & size of bottom Navbar Icons on Book N Buy Project
  assets/css/book.css
Labels: SSOC, Beginner

#819 Added Food master Project
  Public/Foodmaster.html
  assets/Images/Food Master.png
  cards.json
Labels: SSOC, Advance

#892 Changed the position of contact buttons in Animated Portfolio
  Public/AnimatedPortfolio.html
Labels: review-done, SSOC, Beginner

#902 Added Font Styles website
  Public/font_styles.html
  assets/Images/font_logo.jpg
  assets/Js/font_styles.js
  assets/css/font_styles.css
  cards.json
Labels: SSOC, Advance
