Repository ZeroOctave/ZeroOctave-Javascript-Projects, pull requests merged in 2022-03, with the labels that each got.

#192 calculator app opening issue solved
  Public/calculator.html
Labels: Level1

#226 docs: Added PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Level1, GSSoC22

#209 Landing
  assets/Images/analog.jpg
  assets/Images/auto-write.jpg
  assets/Images/calculator.jpg
  assets/Images/color-flipper-1.jpg
  assets/Images/color-flipper-2.jpg
  assets/Images/digital.jpg
  assets/Images/landing1.png
  assets/Images/landing2.png
  assets/Images/quiz.jpg
  assets/Images/restaurant.jpg
  assets/Images/speed_typer.jpg
  index.html
  script.js
  style.css
Labels: GSSoC22, Level3

#204 Added Breakout, Tic-tac-toe, Pokemon generator and Candy crush projects
  Public/breakout.html
  Public/candy_crush.html
  Public/pokemon-generator.html
  Public/tic-tac-toe.html
  assets/Images/Breakout.PNG
  assets/Images/Pokemon.PNG
  assets/Images/Tic-Tac-Toe.PNG
  assets/Images/candy-crush-images.png
  assets/Images/candy-crush-images/Candy-Crush.PNG
  assets/Images/candy-crush-images/blue-candy.png
  assets/Images/candy-crush-images/green-candy.png
  assets/Images/candy-crush-images/orange-candy.png
  assets/Images/candy-crush-images/purple-candy.png
  assets/Images/candy-crush-images/red-candy.png
  assets/Images/candy-crush-images/yellow-candy.png
  assets/Js/breakout.js
  assets/Js/candy_crush.js
  assets/Js/pokemon-generator.js
  assets/Js/tic-tac-toe.js
  assets/css/breakout.css
  assets/css/candy-crush.css
  assets/css/pokemon-generator.css
  assets/css/tic-tac-toe.css
  index.html
Labels: GSSoC22, Level3

#252 added projects to the landing page
  assets/Images/3dsolarsystem.png
  assets/Images/accordion.png
  assets/Images/aipanart.png
  assets/Images/autoimageslider.png
  assets/Images/bmicalculator.png
  assets/Images/countdownclock.png
  assets/Images/counter.png
  assets/Images/drumkit.png
  assets/Images/foodwebsite.png
  assets/Images/heightconverter.png
  assets/Images/hulu.png
  assets/Images/imageeditor.png
  assets/Images/loancalculator.png
  assets/Images/magicnote.png
  assets/Images/mathformule.png
  assets/Images/modalwindow.png
  assets/Images/ngo.png
  assets/Images/noteapp.png
  assets/Images/popup.png
  assets/Images/randomcolorgenerator.png
  assets/Images/responsivenavbar.png
  assets/Images/resumebuilder.png
  assets/Images/rolldice.png
  assets/Images/speed.png
  assets/Images/spotifyclone.png
  assets/Images/stonepaperscissor.png
  assets/Images/tipcalculator.png
  assets/Images/weather.png
  assets/Images/weightconverter.png
  assets/Images/wordcountcalculator.png
  index.html
Labels: Level2, GSSoC22

#251 changed color of passage to make it visible
  style.css
Labels: Level1, GSSoC22

#257 Add Library Website
  Public/BooksLibrary.html
  assets/Images/booksLibrary.png
  assets/Js/BooksLibrary.js
  index.html
Labels: Level2, GSSoC22

#274 #175-(new PR)updated weather ui
  Public/weather_app.html
  assets/css/weather_app.css
Labels: Level1, GSSoC22

#273 Add guess the Number Game
  Public/guess-the-number.html
  assets/Images/guess-the-number.png
  assets/Js/guess-the-number.js
  assets/css/guess-the-number.css
  index.html
Labels: Level2, GSSoC22

#297 crypto-app added
  Public/crypto_app.html
  assets/Images/crypto.jpg
  assets/Js/crypto_app.js
  assets/css/crypto_app.css
  index.html
Labels: GSSoC22, Level3

#265 the id of the card displayed is renamed
  index.html
Labels: Level1, GSSoC22

#266 made the try now button to not go down when letters are popped
  assets/css/landing_page.css
  index.html
Labels: Level1, GSSoC22

#271 Added Dino Game files
  Public/dino-game.html
  assets/Images/dino-game/DinosaurGame bg.jpg
  assets/Images/dino-game/DinosaurGame cactus.png
  assets/Images/dino-game/DinosaurGame character.webp
  assets/Js/dino-game.js
  assets/css/dino-game.css
Labels: Level2, GSSoC22

#300 Added scientific calculator
  Public/scientific_calculator.html
  assets/Images/scientific_calculator.png
  assets/Js/scientific_calculator.js
  assets/css/scientific_calculator.css
  index.html
Labels: Level2, GSSoC22

#306 Fixed the issue #303
  Public/GitHub-Profiles.html
  assets/Js/GitHub-Profiles.js
  assets/css/GitHub-Profiles.css
Labels: Level2, GSSoC22

#307 Added the GitHub-Profiles Card in index.html File
  assets/Images/GitHub-Profiles.jpeg
  index.html
Labels: Level1, GSSoC22

#299 Added real world game features to project car-race
  .DS_Store
  Public/.DS_Store
  Public/car-race.html
  assets/.DS_Store
  assets/Audio/.DS_Store
  assets/Audio/car-race/.DS_Store
  assets/Audio/car-race/Click.mp3
  assets/Audio/car-race/eat.wav
  assets/Audio/car-race/lose.wav
  assets/Audio/drum_kit/.DS_Store
  assets/Js/.DS_Store
  assets/Js/car-race.js
  assets/css/.DS_Store
  assets/css/car-race.css
Labels: GSSoC22, Level3

#311 Prime Factor Calculator using Sieve of Eratosthenes
  Public/primeCalc.html
  assets/Images/primeCalc.png
  assets/Js/primeCalc.js
  assets/css/primeCalc.css
  index.html
Labels: Level1, GSSoC22

#310 Added Random anime profile pic generator to the project list
  Public/animeApp.html
  assets/css/animeApp.css
Labels: Level1, GSSoC22

#305 Added BaseX_Calculator files
  Public/BaseX_Calculator.html
  assets/Js/BaseX_Calculator.js
  assets/css/BaseX_Calculator/style.css
Labels: Level1, GSSoC22

#292 added a new file i.e., Word_Definition
  Public/word_definition.html
  assets/Images/word_definition.jpg
  assets/Js/word_definition.js
  assets/css/word_definition.css
  index.html
Labels: Level1, GSSoC22

#277 Improve responsiveness
  assets/css/landing_page.css
  index.html
  style.css
Labels: Level1, GSSoC22

#244 Speech to text Converter program added
  Public/Speech-to-Text-Converter.html
  assets/Images/speech.png
  assets/Js/speech-to-text-converter.js
  assets/css/speech-to-text-converter.css
  index.html
Labels: Level2, GSSoC22

#334 Speed_Typer Program modified
  Public/Speed_Typer.html
Labels: Level1, GSSoC22

#326 Ice Cream Maker files added
  Public/dictionary.html
  Public/icecream.html
  Public/pong.html
  assets/Images/Dictionary.PNG
  assets/Images/Ice-Cream.PNG
  assets/Images/Pong-Game.PNG
  assets/Js/Ball.js
  assets/Js/Paddle.js
  assets/Js/dictionary.js
  assets/Js/icecream.js
  assets/Js/pong.js
  assets/css/dictionary.css
  assets/css/ice-cream.css
  assets/css/pong.css
  index.html
Labels: Level2, GSSoC22

#324 Pong game files added
  Public/pong.html
  assets/Images/Pong-Game.PNG
  assets/Js/Ball.js
  assets/Js/Paddle.js
  assets/Js/pong.js
  assets/css/pong.css
  index.html
Labels: Level2, GSSoC22

#318 Login form new design
  Public/loginform.html
  assets/Js/loginform.js
  assets/css/loginform.css
Labels: Level1, GSSoC22

#342 Sneaker Site files added
  Public/sneaker.html
  assets/Images/Nike1.PNG
  assets/Images/sneaker-images/air.png
  assets/Images/sneaker-images/air2.png
  assets/Images/sneaker-images/blazer.png
  assets/Images/sneaker-images/blazer2.png
  assets/Images/sneaker-images/contact.png
  assets/Images/sneaker-images/crater.png
  assets/Images/sneaker-images/crater2.png
  assets/Images/sneaker-images/facebook.png
  assets/Images/sneaker-images/gift.png
  assets/Images/sneaker-images/hippie.png
  assets/Images/sneaker-images/hippie2.png
  assets/Images/sneaker-images/instagram.png
  assets/Images/sneaker-images/jordan.png
  assets/Images/sneaker-images/jordan2.png
  assets/Images/sneaker-images/master.png
  assets/Images/sneaker-images/return.png
  assets/Images/sneaker-images/search.png
  assets/Images/sneaker-images/shipping.png
  assets/Images/sneaker-images/sneakers.png
  assets/Images/sneaker-images/twitter.png
  assets/Images/sneaker-images/visa.png
  assets/Images/sneaker-images/whatsapp.png
  assets/Js/sneaker.js
  assets/css/sneaker.css
  index.html
Labels: Level2, GSSoC22

#336 Modified Drum kit
  Public/drum_kit.html
  assets/Images/crash.png
  assets/Images/drumkit.png
  assets/Images/drumkit_BG.png
  assets/Images/kick.png
  assets/Images/snare.png
  assets/Images/tom1.png
  assets/Images/tom2.png
  assets/Images/tom3.png
  assets/Images/tom4.png
  assets/css/drum_kit.css
Labels: Level1, GSSoC22

#275 Improve the UI feature of BMI Calculator Project
  Public/bmi-calculator.html
  assets/Images/BMI_Calculator_image_landing_page.png
  assets/Images/Fitness_Background_bmi.jpg
  assets/Images/bmicalculator.png
  assets/Js/bmi-calculator.js
  assets/css/bmi-calculator.css
  index.html
Labels: Level1, GSSoC22

#341 Updated the Readme
  README.md
Labels: Level1, GSSoC22

#333 Added CRUD Project files
  Public/crud-project.html
  assets/Images/Crud.png
  assets/Js/crud-project.js
  assets/css/crud-project.css
  index.html
Labels: Level2, GSSoC22

#347 Added Currency Converter
  Public/Currency-converter.html
  assets/Images/Currency-converter.PNG
  assets/Js/Currency-converter.js
  assets/css/Currency-converter.css
  index.html
Labels: Level2, GSSoC22

#356 Added hangman game in javascript4
  Public/hangman.html
  assets/Audio/click.mp3
  assets/Audio/lost.wav
  assets/Audio/win.wav
  assets/Images/Web view.PNG
  assets/Images/hangman.png
  assets/Images/mobile view.PNG
  assets/Js/hangman.js
  assets/css/hangman.css
  index.html
Labels: GSSoC22, Level3

#267 Added Color Code Converter Files
  Public/Color_Code_Converter.html
  assets/Js/Color_Code_Converter.js
  assets/css/Color_Code_Converter.css
Labels: Level2, GSSoC22

#351 Added Dark Mode to counter
  Public/counter.html
  assets/Js/counter.js
  assets/css/counter.css
Labels: Level1, GSSoC22

#368 Add projects in README.md
  README.md
Labels: Level1, GSSoC22

#353 Dictionary_App_Improvements done...
  Public/dictionary.html
  assets/Js/dictionary.js
  assets/css/dictionary.css
  index.html
Labels: Level2, GSSoC22

#360 Added my developer portfolio website
  Public/multiple-portfolio.html
  assets/Images/images(portfolio)/banner.jpg
  assets/Images/images(portfolio)/pic.jpg
  assets/Images/images(portfolio)/profile.jpg
  assets/Images/multi-portfolio.png
  assets/Js/multiple-portfolio.js
  assets/css/multiple-portfolio.css
  index.html
Labels: GSSoC22, Level3

#378 Added password generator app in javascript
  Public/password_generator.html
  assets/Images/password generator.png
  assets/Js/password_generator.js
  assets/css/password_generator.css
  index.html
Labels: Level2, GSSoC22

#364 To do list
  Public/to-do.html
  assets/Images/to-do-bg.jpg
  assets/Images/to-do-img.png
  assets/Js/to-do.js
  assets/css/to-do.css
  index.html
Labels: Level2, GSSoC22

#381 Add footer section to the website
  index.html
  style.css
Labels: Level1, GSSoC22

#372 Successfully fixed the issue of Unworking file links of BMI Calculator issue#270
  Public/bmi-calculator.html
  assets/css/bmi-calculator.css
  index.html
Labels: Level1, GSSoC22

#367 Modified word definition webpage
  Public/word_definition.html
  assets/Images/word_definition.png
  assets/Js/word_definition.js
  assets/css/word_definition.css
Labels: Level2, GSSoC22

#380 RD return calculator
  Public/RD-return-calculator.html
  assets/Images/RD-return-calculator.png
  assets/Js/RD-return-calculator.js
  assets/css/RD-return-calculator.css
  index.html
Labels: Level2, GSSoC22

#403 Add Searchbar for the projects
  index.html
  style.css
Labels: Level1, GSSoC22

#404 Added function grapher files
  Public/Function_Grapher.html
  assets/Js/Function_Grapher/app.js
  assets/Js/Function_Grapher/bootstrap.bundle.js
  assets/Js/Function_Grapher/bootstrap.bundle.js.map
  assets/Js/Function_Grapher/function_plot.js
  assets/css/Function_Grapher/bootstrap.css
  assets/css/Function_Grapher/bootstrap.css.map
  assets/css/Function_Grapher/style.css
  index.html
Labels: GSSoC22, Level3

#405 speech synthesis
  Public/speech_synthesis.html
  README.md
  assets/Images/speechsynthesis.png
  assets/Js/speech synthesis.js
  assets/css/speech synthesis.css
  index.html
Labels: Level2, GSSoC22

#400 Added third degree eq solver files
  Public/Third_Degree_Equation_Calculator.html
  assets/Js/Third_Degree_Equation_Solver/app.js
  assets/Js/Third_Degree_Equation_Solver/bootstrap.bundle.js
  assets/Js/Third_Degree_Equation_Solver/bootstrap.bundle.js.map
  assets/css/Third_Degree_Equation_Solver/bootstrap.css
  assets/css/Third_Degree_Equation_Solver/bootstrap.css.map
  assets/css/Third_Degree_Equation_Solver/style.css
  index.html
Labels: Level2, GSSoC22

#408 scroll To Top botton added
  index.html
  style.css
Labels: Level1, GSSoC22

#407 Added Key Detector webpage
  Public/key_Detector.html
  assets/Images/key_Detector.png
  assets/Js/key_Detector.js
  assets/css/key_Detector.css
  index.html
Labels: Level2, GSSoC22

#398 Travel game
  Public/Travel game.html
  assets/Audio/travel game/Ambient-mystic-piano-track.mp3
  assets/Images/travel_game/cloud.png
  assets/Images/travel_game/lights-off.png
  assets/Images/travel_game/lights-on.png
  assets/Images/travel_game/travel.png
  assets/Images/travel_game/way.png
  assets/Js/travel  game.js
  assets/css/travelgame.css
  index.html
Labels: review-done, Level2, GSSoC22

#413 Prikshit gssoc candidate
  cardsData.js
  index.html
  script.js
  style.css
Labels: review-done
