Repository ZeroOctave/ZeroOctave-Javascript-Projects, pull requests merged in 2022-05, with the labels that each got.

#587 Updating UI for Height Converter
  Public/height-converter.html
  assets/Images/awgarriBG.jpg
  assets/css/height-converter.css
Labels: Level1, GSSoC22

#585 Added a Drink Water Application
  Public/drinkwater.html
  README.md
  assets/Js/drinkwater.js
  assets/css/drinkwater.css
Labels: Level2, GSSoC22

#576 Added News Website
  Public/News_Site.html
  README.md
  assets/Images/NewsWebsite.png
  assets/Js/News_Site/app3.js
  assets/Js/News_Site/app3b.js
  assets/css/News_Site.css
  cards.json
Labels: Level2, GSSoC22

#586 Added URL keeper Application
  Public/url_keeper.html
  README.md
  assets/Images/url_keeper.png
  assets/Images/url_keeper_icon.png
  assets/Js/url_keeper.js
  assets/css/url_keeper.css
Labels: Level2, GSSoC22

#590 adding blurry loading
  Public/blurry-loading.html
  README.md
  assets/Images/blurry-loading.png
  assets/Js/blurry-loading.js
  assets/css/blurry-loading.css
  cards.json
Labels: Level2, GSSoC22

#593 Added hover effect to navbar in Al Panart resolved issue #588
  Public/aipanArt.html
Labels: Level1, GSSoC22

#616 Added dad's Joke application
  Public/dadsjoke.html
  README.md
  assets/Images/dadsjoke.jpg
  assets/Js/dadsjoke.js
  assets/css/dadsjoke.css
  cards.json
Labels: Level2, GSSoC22

#620 Added A Clock project with dark and light theme
  Public/theme-clock.html
  README.md
  assets/Images/theme-clock.png
  assets/Js/theme-clock.js
  assets/css/theme-clock.css
  cards.json
Labels: Level2, GSSoC22

#621 Fixed Image links that were not visible
  cards.json
Labels: Level1, GSSoC22

#624 Browser Detector
  Public/Browser_Detector.html
  README.md
  assets/Images/BrowserDetector/Edge.png
  assets/Images/BrowserDetector/Google_Chrome.png
  assets/Images/BrowserDetector/Mozilla_Firefox.png
  assets/Images/BrowserDetector/Opera.png
  assets/Images/BrowserDetector/main.png
  assets/Images/BrowserDetector/safari.png
  assets/Js/Browser_Detector.js
  assets/css/Browser_Detector.css
  cards.json
Labels: Level2, GSSoC22

#623 Added vaccine slot finder
  Public/vaccineslot.html
  README.md
  assets/Images/vaccineslot/vaccineslot.jpg
  assets/Images/vaccineslot/vaccineslotadd.png
  assets/Js/vaccineslot.js
  assets/css/vaccineslot.css
  cards.json
Labels: GSSoC22, Level3

#632 Sudoku Solver
  Public/SudokuSolver.html
  README.md
  assets/Images/SudokuSolver.png
  assets/Js/SudokuSolver.js
  assets/css/SudokuSolver.css
  cards.json
Labels: Level2, GSSoC22

#628 Candy Store Html, CSS and JavaScript
  Public/Candy Store/Menu.htm
  Public/Candy Store/checkout.html
  Public/Candy Store/index.htm
  Public/Candy Store/thankyou.html
  README.md
  assets/Images/Candy Store/1.jpg
  assets/Images/Candy Store/1x.jpg
  assets/Images/Candy Store/2x.jpg
  assets/Images/Candy Store/3x.jpg
  assets/Images/Candy Store/Spinner.gif
  assets/Images/Candy Store/bear.png
  assets/Images/Candy Store/bear0.jpg
  assets/Images/Candy Store/bear1.jpg
  assets/Images/Candy Store/bg.webp
  assets/Images/Candy Store/chocolate.jpg
  assets/Images/Candy Store/contact.jpg
  assets/Images/Candy Store/contact2.jpg
  assets/Images/Candy Store/cotton.jpg
  assets/Images/Candy Store/cover1.jpg
  assets/Images/Candy Store/cover2.jpg
  assets/Images/Candy Store/cover3.jpg
  assets/Images/Candy Store/coverimg.jpg
  assets/Images/Candy Store/dark.jpg
  assets/Images/Candy Store/dd.png
  assets/Images/Candy Store/downArrow.png
  assets/Images/Candy Store/dw.gif
  assets/Images/Candy Store/g.jpg
  assets/Images/Candy Store/gumball.png
  assets/Images/Candy Store/hand2.png
  assets/Images/Candy Store/k.jpg
  assets/Images/Candy Store/kosher.jpg
  assets/Images/Candy Store/l.jpg
  assets/Images/Candy Store/lolli_icon.png
  assets/Images/Candy Store/lollipop.jpg
  assets/Images/Candy Store/milk.png
  assets/Images/Candy Store/p.jpg
  assets/Images/Candy Store/p1.jpg
  assets/Images/Candy Store/r.jpg
  assets/Images/Candy Store/s.jpg
  assets/Images/Candy Store/sprinkles.png
  assets/Images/Candy Store/swt.jpg
  assets/Images/Candy Store/ut.png
  assets/Images/Candy Store/utensil.png
  assets/Images/Candy Store/white.jpg
  assets/Js/Candy Store/js.js
  assets/Js/Candy Store/menu.js
  assets/css/Candy Store/Menu.css
  assets/css/Candy Store/Spinner.gif
  assets/css/Candy Store/bg.webp
  assets/css/Candy Store/checkout.css
  assets/css/Candy Store/contact2.jpg
  assets/css/Candy Store/firstProject.css
  cards.json
Labels: GSSoC22, Level3

#650 Country Capital Webpage
  Public/Country Capital Page/README.md
  Public/country_capital_homepage.html
  README.md
  assets/Images/country_capital_homepage/bg.jpg
  assets/Js/country_capital_homepage.js
  assets/css/country_capital_homepage.css
  cards.json
Labels: Level2, GSSoC22

#652 Added flappy bird game
  Public/flappybird.html
  README.md
  assets/Audio/flappybird/fly.mp3
  assets/Audio/flappybird/score.mp3
  assets/Images/flappybird/bg.jpg
  assets/Images/flappybird/bird4.png
  assets/Images/flappybird/flappybird.png
  assets/Images/flappybird/pipeNorth.png
  assets/Images/flappybird/pipeSouth.png
  assets/Js/flappybird.js
  cards.json
Labels: GSSoC22, Level3

#667 Added Connect Four Game in Html CSS and JS
  Public/connectfour.html
  README.md
  assets/Audio/connectfour/click.mp3
  assets/Audio/connectfour/lost.wav
  assets/Audio/connectfour/win.wav
  assets/Images/connectfour.png
  assets/Js/connectfour.js
  assets/css/connectfour.css
  cards.json
Labels: GSSoC22, Level3

#597 Coin-Toss-Game
  Public/Coin-toss-game.html
  README.md
  assets/Images/Coin-Toss-Game.jpeg
  assets/Images/coin-toss-heads.svg
  assets/Images/coin-toss-tails.svg
  assets/Js/.DS_Store
  assets/Js/coin-toss.js
  assets/css/coin-toss.css
  cards.json
Labels: Level2, GSSoC22

#685 Added reset password option in login form
  Public/loginform.html
  assets/Images/loginbackgroundimage.jpg
  assets/Js/loginform.js
  assets/css/loginform.css
Labels: Level2

#684 Movie recommendation page
  Public/Country Capital Page/README.md
  Public/movies_rec.html
  README.md
  assets/Images/movies_rec.jpg
  assets/Js/movies_rec.js
  assets/css/movies_rec.css
  cards.json
Labels: Level1, GSSoC22

#680 Modified Tic Tac Toe
  Public/tic-tac-toe.html
  assets/Js/tic-tac-toe.js
  assets/Js/tic-tac-toe/bootstrap.min.js
  assets/Js/tic-tac-toe/jquery-3.5.1.slim.min.js
  assets/Js/tic-tac-toe/main.js
  assets/Js/tic-tac-toe/popper.min.js
  assets/css/tic-tac-toe.css
  assets/css/tic-tac-toe/bootstrap.min.css
  assets/css/tic-tac-toe/main.css
Labels: Level2, GSSoC22

#683 Random Choice Picker
  Public/RandomChoicePicker.html
  README.md
  assets/Js/RandomChoicePicker.js
  assets/css/RandomChoicePicker.css
Labels: Level2, GSSoC22

#711 GitHub profile not work
  Public/GitHub-Profiles.html
Labels: Level1, GSSoC22

#717 Added moving car animation
  Public/movingcar.html
  README.md
  assets/Audio/sound.mp3
  assets/Images/movingcar/background.jpg
  assets/Images/movingcar/car_body.png
  assets/Images/movingcar/car_wheel_left.png
  assets/Images/movingcar/car_wheel_right.png
  assets/Images/movingcar/movingcar.png
  assets/Images/movingcar/mycar.png
  assets/Images/movingcar/track.png
  assets/Images/movingcar/trees.png
  assets/Js/movingcar.js
  assets/css/movingcar.css
  cards.json
Labels: Level1, GSSoC22

#678 Improved Image App
  Public/image_editor.html
  assets/Images/Image-Filter-App.png
  assets/Js/image_editor.js
  assets/css/image_editor.css
  cards.json
Labels: Level2, GSSoC22

#723 Added Postman Clone Website
  Public/postmaster.html
  README.md
  assets/Images/postmaster/logo.png
  assets/Images/postmaster/postmaster.png
  assets/Js/postmaster/postmaster.js
  assets/Js/postmaster/prism.js
  assets/css/postmaster/prism.css
  cards.json
Labels: Level2, GSSoC22

#721 Same image
  assets/Images/Todo.png
  cards.json
Labels: Level1, GSSoC22

#704 Made meditation website responsive
  assets/css/meditation.css
Labels: Level1, GSSoC22

#734 Added Wordle Clone
  Public/Wordle-clone.html
  README.md
  assets/Images/Wordle-clone.PNG
  assets/Js/Wordle-clone.js
  assets/css/Wordle-clone.css
  cards.json
Labels: GSSoC22, Level3

#702 Feedbackthankyou
  Public/FeedbackThankyou.html
  README.md
  assets/Images/FeedbackThankyou/FeedbackThankyou.png
  assets/Images/FeedbackThankyou/bad.jpg
  assets/Images/FeedbackThankyou/good.jpg
  assets/Images/FeedbackThankyou/moderate.png
  assets/Images/FeedbackThankyou/reply.jpg
  assets/Images/RandomChoicePicker.png
  assets/Js/FeedbackThankyou.js
  assets/css/FeedbackThankyou.css
  cards.json
Labels: Level1, GSSoC22

#739 Responsive Range-Slider Added!
  Public/RangeSlider.html
  README.md
  assets/Js/rangeSlider.js
  assets/css/rangeSlider.css
  cards.json
Labels: Level1, GSSoC22

#732 Vigenere Cipher Added
  Public/VigenereCipher.html
  README.md
  assets/Images/VigenereCipher.png
  assets/Js/VigenereCipher.js
  assets/css/VigenereCipher.css
  cards.json
Labels: Level2, GSSoC22

#740 ExpandingCradsUIdesign html,css,js
  Public/ExpandingCardsUIdesign.html
  README.md
  assets/Images/ExpandingCardsUIdesign.png
  assets/Js/ExpandingCardsUIdesign.js
  assets/css/ExpandingCardsUIdesign.css
  cards.json
Labels: Level2, GSSoC22

#747 Switching Testimonial Box
  Public/SwitchingTestimonialBox.html
  README.md
  assets/Images/SwitchingTestimonialBox.png
  assets/Js/SwitchingTestimonialBox.js
  assets/css/SwitchingTestimonialBox.css
  cards.json
Labels: Level1, GSSoC22

#746 Grocery manager added
  Public/grocerymanager.html
  README.md
  assets/Images/grocerymanager.png
  assets/Js/grocerymanager.js
  assets/css/grocerymanager.css
  cards.json
Labels: Level1, GSSoC22

#598 Added Reflex Training Game
  Public/Reflex_Training.html
  README.md
  assets/Images/Reflex_Training/Reflex.png
  assets/Images/Reflex_Training/countdown.gif
  assets/Images/Reflex_Training/target_PNG38.png
  assets/Js/Reflex_training.js
  assets/css/Reflex_training.css
  cards.json
Labels: Level2, GSSoC22

#674 CV screener issue no 669
  Public/CV-Screener.html
  README.md
  assets/Js/Cv-screener.js
  cards.json
Labels: Level1, GSSoC22

#755 Switching Testimonial Box
  Public/SwitchingTestimonialBox.html
  README.md
  assets/Images/SwitchingTestimonialBox.png
  assets/Js/SwitchingTestimonialBox.js
  assets/css/SwitchingTestimonialBox.css
  cards.json
Labels: Level1, GSSoC22

#700 2048 Game
  Public/2048.html
  README.md
  assets/Images/2048.png
  assets/Js/2048.js
  assets/css/2048.css
  cards.json
Labels: Level2, GSSoC22

#764 Added color game
  Public/color-game.html
  README.md
  assets/Js/Color-game.js
  assets/css/color-game.css
  cards.json
Labels: Level2, GSSoC22

#768 Tourist Website added
  Public/Tourist_Website/About.html
  Public/Tourist_Website/Gallery.html
  Public/Tourist_Website/index.html
  README.md
  assets/Images/Tourist_Website/Skardu.jpg
  assets/Images/Tourist_Website/Skardu1.jpg
  assets/Images/Tourist_Website/isb.jpg
  assets/Images/Tourist_Website/kash.jpg
  assets/Images/Tourist_Website/kash2.jpg
  assets/Images/Tourist_Website/khi.jpg
  assets/Images/Tourist_Website/lhr.jpg
  assets/Images/Tourist_Website/lhr0.jpg
  assets/Images/Tourist_Website/lhr00.jpg
  assets/Images/Tourist_Website/lhr2.jpg
  assets/Images/Tourist_Website/lhr3.jpg
  assets/Images/Tourist_Website/loader.gif
  assets/Images/Tourist_Website/pakistan.gif
  assets/Images/Tourist_Website/palace.jpg
  assets/Images/Tourist_Website/sku.jpg
  assets/Images/Tourist_Website/sku1.jpg
  assets/Images/Tourist_Website/swt.jpg
  assets/Images/Tourist_Website/swt1.jpg
  assets/Images/Tourist_Website/swt2.jpg
  assets/Images/Tourist_Website/swt3.jpg
  assets/Js/Tourist_Website/about.js
  assets/Js/Tourist_Website/gallery.js
  assets/Js/Tourist_Website/work.js
  assets/css/Tourist_Website/about.css
  assets/css/Tourist_Website/gallery.css
  assets/css/Tourist_Website/style.css
  cards.json
Labels: GSSoC22, Level3

#769 AudioPlay
  Public/AudioPlay.html
  README.md
  assets/Audio/AudioPlay/angry.wav
  assets/Audio/AudioPlay/applause.wav
  assets/Audio/AudioPlay/astonish.wav
  assets/Audio/AudioPlay/laugh.wav
  assets/Audio/AudioPlay/sneeze.wav
  assets/Audio/AudioPlay/whistle.wav
  assets/Images/AudioPlay.png
  assets/Js/AudioPlay.js
  assets/css/AudioPlay.css
  cards.json
Labels: Level2, GSSoC22

#761 Add a Tearable Cloth Project
  Public/tearable-cloth.html
  README.md
  assets/Images/tearable-cloth.png
  assets/Js/tearable-cloth.js
  assets/css/tearable-cloth.css
  cards.json
Labels: GSSoC22, Level3

#690 Rain Effects
  Public/RainEffects.html
  README.md
  assets/Images/RainEffects.jpg
  assets/Js/RainEffects.js
  assets/css/RainEffects.css
  cards.json
Labels: Level1, GSSoC22

#773 Camera Web Application
  Public/camera_app.html
  README.md
  assets/Images/camera.PNG
  cards.json
Labels: Level1, GSSoC22

#762 Added Picture-frame
  Public/picture-frame.html
  README.md
  assets/Images/picture-frame.jpg
  assets/Js/picture-frame.js
  assets/css/picture-frame.css
  cards.json
Labels: Level1, GSSoC22

#778 FAQcollapse
  Public/FAQcollapse.html
  README.md
  assets/Images/FAQcollapse.png
  assets/Js/FAQcollapse.js
  assets/css/FAQcollapse.css
  cards.json
Labels: Level1, GSSoC22

#777 Multiplication Table Generator, resolving issue #653
  Public/multiplication-table-generator.html
  README.md
  assets/Images/images.jpg
  assets/Js/mtg.js
  assets/css/mtg.css
  cards.json
Labels: Level2, GSSoC22
