Repository ZeroOctave/ZeroOctave-Javascript-Projects, pull requests merged in 2022-08, with the labels that each got.

#834 trainer spelling corrected in gym-website
  Public/gym-website.html
Labels: good first issue, review-done, SSOC

#825 Updated guess-the-number.html Check and Again button are now responding
  Public/guess-the-number.html
Labels: review-done, SSOC

#826 Improvement in the UI of BMI Calculator Web Application
  Public/bmi-calculator.html
  assets/Images/background-fitness-bmi.jpg
  assets/Js/bmi-calculator.js
  assets/css/bmi-calculator.css
Labels: SSOC, Beginner

#829 Book type button click fix
  Public/BooksLibrary.html
Labels: SSOC, Beginner

#836 Now we can navigate within same webpage using navigation bar
  Public/gym-website.html
  assets/css/gym-website.css
Labels: review-done, SSOC, Intermediate

#854 Added my "Recipe" website
  Public/SimplyRecipes/404.html
  Public/SimplyRecipes/about.html
  Public/SimplyRecipes/contact.html
  Public/SimplyRecipes/food/banana_pancakes.html
  Public/SimplyRecipes/food/burger.html
  Public/SimplyRecipes/food/carrot.html
  Public/SimplyRecipes/food/crispy-chicken.html
  Public/SimplyRecipes/food/danish_pastry.html
  Public/SimplyRecipes/food/fish_curry.html
  Public/SimplyRecipes/food/fried-chicken.html
  Public/SimplyRecipes/food/pizza.html
  Public/SimplyRecipes/food/sandwich.html
  Public/SimplyRecipes/index.html
  Public/SimplyRecipes/recipes.html
  Public/SimplyRecipes/tags.html
  Public/SimplyRecipes/tags/breakfast_tag.html
  Public/SimplyRecipes/tags/carrots_tag.html
  Public/SimplyRecipes/tags/chicken_tag.html
  Public/SimplyRecipes/tags/dinner_tag.html
  assets/Images/SimplyRecipes/assets/about.jpeg
  assets/Images/SimplyRecipes/assets/favicon.ico
  assets/Images/SimplyRecipes/assets/logo.svg
  assets/Images/SimplyRecipes/assets/main.jpeg
  assets/Images/SimplyRecipes/assets/recipes/burger.jpg
  assets/Images/SimplyRecipes/assets/recipes/crispychicken.jpg
  assets/Images/SimplyRecipes/assets/recipes/danish_pastry.jpg
  assets/Images/SimplyRecipes/assets/recipes/fishcurry.jpg
  assets/Images/SimplyRecipes/assets/recipes/friedchicken.jpg
  assets/Images/SimplyRecipes/assets/recipes/pizza.jpg
  assets/Images/SimplyRecipes/assets/recipes/recipe-1.jpeg
  assets/Images/SimplyRecipes/assets/recipes/recipe-2.jpeg
  assets/Images/SimplyRecipes/assets/recipes/recipe-3.jpeg
  assets/Images/SimplyRecipes/assets/recipes/recipe-4.jpeg
  assets/Images/SimplyRecipes/assets/recipes/sandwich.jpg
  assets/Js/SimplyRecipes/js/app.js
  assets/css/SimplyRecipes/css/main.css
  assets/css/SimplyRecipes/css/normalize.css
  cards.json
Labels: review-done, SSOC, Advance

#865 fixing the calculate button
  Public/BaseX_Calculator.html
Labels: review-done, SSOC, Beginner

#855 fixed typo issue
  Public/popup.html
Labels: Beginner

#845 Redesigned Spotify Clone
  Public/spotify-clone.html
  assets/Images/Spotifyclonecards.png
  assets/Images/spotify (10).jpg
  assets/Images/spotify (11).jpg
  assets/Images/spotify (12).jpg
  assets/Images/spotify (2).jpg
  assets/Images/spotify (3).jpg
  assets/Images/spotify (4).jpg
  assets/Images/spotify (5).jpg
  assets/Images/spotify (6).jpg
  assets/Images/spotify (7).jpg
  assets/Images/spotify (8).jpg
  assets/Images/spotify (9).jpg
  assets/Images/spotify image.jpg
  assets/Images/spotify-clone1.jpg
  assets/css/spotify-clone.css
  cards.json
Labels: SSOC, Intermediate
