Repository ZeroOctave/ZeroOctave-Javascript-Projects, pull requests merged in 2022-10, with the labels that each got.

#896 Adding footer and hover effect in myntra clone
  Public/myntraclone.html
  assets/Images/126472.png
  assets/Images/app-store.png
  assets/Images/download on app store
  assets/Images/google-play.png
  assets/Js/myntraclone.js
  assets/css/myntraclone.css
Labels: review-done, SSOC, Intermediate

#905 Added buttons for x^2, x^y, sqrt(x), log(x) , 兀, e in Calculator
  Public/calculator.html
  assets/Js/Calculator.js
  assets/css/Calculator.css
Labels: hacktoberfest-accepted

#931 Employee database
  Public/employeeDatabase.html
  README.md
  assets/Images/employeeDatabase.png
  assets/Js/employeeDatabase.js
  assets/css/employeeDatabase.css
  cards.json
Labels: review-done
