Repository ZeroOctave/ZeroOctave-Javascript-Projects, pull requests merged in 2022-04, with the labels that each got.

#420 Created Tic Tac Toe Game
  Public/tic-tac-toe.html
  assets/Images/tic-tac-toe.PNG
  assets/Js/tic-tac-toe/bootstrap.min.js
  assets/Js/tic-tac-toe/jquery-3.5.1.slim.min.js
  assets/Js/tic-tac-toe/main.js
  assets/Js/tic-tac-toe/popper.min.js
  assets/css/tic-tac-toe/bootstrap.min.css
  assets/css/tic-tac-toe/main.css
  cardsData.js
  index.html
Labels: Level2, GSSoC22

#418 Sticky Notes
  Public/sticky_notes.html
  assets/Images/sticky_notes.png
  assets/Js/sticky_notes.js
  assets/css/sticky_notes.css
  index.html
Labels: Level2, GSSoC22

#433 Added Color Changing App
  Public/Color-Changing-App.html
  assets/Images/color-changing-app.png
  assets/Js/Color-Changing-App.js
  assets/css/Color-Changing-App.css
  cardsData.js
  index.html
Labels: Level2, GSSoC22

#435 Added Movie/TV Series Quote Generator (fixed issue #427)
  Public/MovieQuoteGenerator.html
  assets/Images/MovieQuoteGenerator.png
  assets/Js/MovieQuoteGenerator.js
  assets/css/MovieQuoteGenerator.css
  cardsData.js
  index.html
Labels: Level2, GSSoC22

#441 Solved issue #319 . Counter feature working properly
  assets/Js/counter.js
  assets/Js/word-count-calculator.js
Labels: Level1, GSSoC22

#437 Back to top button bug resolved
  index.html
  style.css
Labels: Level1, GSSoC22

#414 Added "QR Code Generator" webpage
  Public/QR_Code_Generator.html
  assets/Images/QR_Code_Generator.png
  assets/Js/QR_Code_Generator.js
  assets/css/QR_Code_Generator.css
  cardsData.js
  index.html
Labels: Level1, GSSoC22

#474 CaesarCipher Program modified
  Public/CaesarCipher.html
  assets/css/CaesarCipher.css
Labels: Level1, GSSoC22

#473 Added Drawing App
  Public/drawingapp.html
  assets/Images/drawingapp.png
  assets/Js/drawingapp.js
  assets/css/drawingapp.css
  cardsData.js
  index.html
Labels: Level2, GSSoC22

#470 Add projects to README.md
  README.md
Labels: Level1, GSSoC22

#475 Added Animated Project
  Public/AnimatedPortfolio.html
  assets/Images/gmail_logo_PNG2.png
  assets/Images/—Pngtree—call icon png_3621527.png
  assets/Images/—Pngtree—linkedin social media icon_3609691.png
Labels: Level1, GSSoC22

#499 Added Palindrome Checker
  Public/palindrome.html
  assets/Images/Palindrome Checker.png
  assets/Images/bgi5.jpg
  assets/Js/palindrome.js
  assets/css/palindrome.css
  cardsData.js
  index.html
Labels: Level1, GSSoC22

#484 Add a book shopping website
  Public/book-shopping-website/book.html
  Public/book-shopping-website/cart.html
  assets/Images/bookshopimgs/20-Best-Romantic-Novels-in-English.jpeg
  assets/Images/bookshopimgs/7 habits.jpeg
  assets/Images/bookshopimgs/Divergent_(book)_by_Veronica_Roth_US_Hardcover_2011.jpeg
  assets/Images/bookshopimgs/a-6th-bowl-of-chicken-soup-for-the-soul-9781623610739_hr.jpeg
  assets/Images/bookshopimgs/alchemist.jpeg
  assets/Images/bookshopimgs/almond son won pyeong.jpeg
  assets/Images/bookshopimgs/becoming michelle.jpeg
  assets/Images/bookshopimgs/bookbuy5.png
  assets/Images/bookshopimgs/breath james nestor.jpeg
  assets/Images/bookshopimgs/capital thomas picketty.jpeg
  assets/Images/bookshopimgs/chocolate factory.jpeg
  assets/Images/bookshopimgs/deal.jpeg
  assets/Images/bookshopimgs/doawk.jpeg
  assets/Images/bookshopimgs/educated+by+tara+westover.jpeg
  assets/Images/bookshopimgs/elderly.jpeg
  assets/Images/bookshopimgs/fios.jpeg
  assets/Images/bookshopimgs/goosebumps.jpeg
  assets/Images/bookshopimgs/half-sick-of-shadows-book-cover-1-506x765.jpeg
  assets/Images/bookshopimgs/harry potter.jpeg
  assets/Images/bookshopimgs/i-am-malala-1533929974.jpeg
  assets/Images/bookshopimgs/ikigai garcia & miralles.jpeg
  assets/Images/bookshopimgs/kid read.jpeg
  assets/Images/bookshopimgs/kindle.jpg
  assets/Images/bookshopimgs/klara and the sun.jpg
  assets/Images/bookshopimgs/kristin hannah.jpeg
  assets/Images/bookshopimgs/mitch albom the stranger in the lifeboat.jpeg
  assets/Images/bookshopimgs/orient express.jpeg
  assets/Images/bookshopimgs/read vs listen.jpeg
  assets/Images/bookshopimgs/read.jpeg
  assets/Images/bookshopimgs/sita amish.jpeg
  assets/Images/bookshopimgs/the chanel sisters judithe little.jpeg
  assets/Images/bookshopimgs/the last thing he told me laura dave.jpeg
  assets/Images/bookshopimgs/the lean startup eric ries.jpeg
  assets/Images/bookshopimgs/the midnight library.jpeg
  assets/Images/bookshopimgs/the wife upstairs.jpeg
  assets/Images/bookshopimgs/the-diary-of-a-young-girl-27.jpeg
  assets/Images/bookshopimgs/think straight darius foroux.jpeg
  assets/Images/bookshopimgs/while justice sleeps.jpeg
  assets/Images/bookshopimgs/white wood 2.jpeg
  assets/Images/bookshopimgs/will smith book.jpeg
  assets/Js/book-shopping-website/book.js
  assets/Js/book-shopping-website/cart.js
  assets/css/book.css
  cardsData.js
  index.html
Labels: Level2, GSSoC22

#476 Added Responsive Landing Page with Dark and light toggle
  Public/responsiveLanding.html
  assets/Images/ResponsiveLanding/logo.png
  assets/Images/ResponsiveLanding/person.png
  assets/Images/ResponsiveLanding/shape.png
  assets/Images/responsiveWeb.png.png
  assets/Js/responsiveLanding.js
  assets/css/responsiveLanding.css
  index.html
Labels: Level1, GSSoC22

#496 Add website favicon
  index.html
  web_favicon.ico
Labels: Level1, GSSoC22

#457 Added Stopwatch Application
  Public/stopwatch.html
  assets/Images/stopwatch.png
  assets/Js/stopwatch.js
  assets/css/stopwatch.css
  cardsData.js
  index.html
Labels: Level1, GSSoC22

#520 backend setup
  Public/mapty.html
  assets/Images/Basex.JPG
  assets/Images/animated.JPG
  assets/Images/colorchooser.JPG
  assets/Images/emailval.JPG
  assets/Images/functiongrapher.JPG
  assets/Images/maps.JPG
  assets/Images/modal2.JPG
  assets/Images/numberguess.JPG
  assets/Images/passval.JPG
  assets/Images/placeholder.JPG
  assets/Images/quiz.jpg
  assets/Images/quizapp.JPG
  assets/Images/report.JPG
  assets/Images/rev.JPG
  assets/Images/snake.JPG
  assets/Images/social.JPG
  assets/Images/solar.JPG
  assets/Images/tapmusic.JPG
  assets/Images/toast.JPG
  assets/Images/xxx.JPG
  cards.json
  cardsData.js
  index.html
  style.css
Labels: GSSoC22, Level3

#518 Expense
  Public/expense.html
  README.md
  assets/Images/expense.png
  assets/Js/expense.js
  assets/css/expense.css
  cards.json
Labels: Level2, GSSoC22

#529 added responsiveness
  style.css
Labels: Level1, GSSoC22

#531 15-puzzle-Challenge added
  Public/15puzzle.html
  README.md
  assets/Images/15puzzle.png
  assets/Js/15puzzle.js
  assets/css/15puzzle.css
  cards.json
Labels: Level2, GSSoC22

#548 Added Random Quote Generator
  Public/Random_Quote_Generator.html
  README.md
  assets/Images/Random_Quote.PNG
  assets/Js/Random_Quote_Generator.js
  assets/css/Random_Quote_Generator.css
  cards.json
Labels: Level2, GSSoC22

#536 Fixed Issue 483 - Added Tinder Clone
  Public/Tinder_Clone.html
  README.md
  assets/Images/tinder_clone.jpg
  assets/css/Tinder_Clone.css
  cards.json
Labels: Level1, GSSoC22

#560 Adding Temperature Converter
  Public/temperature-converter.html
  README.md
  assets/Images/temperature-converter.png
  assets/Js/temperature-converter.js
  cards.json
Labels: Level1, GSSoC22

#573 Added GoogleClone1
  Public/googleClone1/advancesearch.html
  Public/googleClone1/googleclone1.html
  Public/googleClone1/images.html
  README.md
  assets/Images/googleclone1/advanced-search.PNG
  assets/Images/googleclone1/favicon.png
  assets/Images/googleclone1/gimage.png
  assets/Images/googleclone1/google.png
  assets/Images/googleclone1/images.PNG
  assets/Js/googleclone1/google.js
  assets/Js/googleclone1/googleimages.js
  assets/css/googleclone1/advancesearch.css
  assets/css/googleclone1/googleclone.css
  assets/css/googleclone1/images.css
  cards.json
Labels: GSSoC22, Level3
