Repository ZeroOctave/ZeroOctave-Javascript-Projects, pull requests merged in 2023-02, with the labels that each got.

#857 feat: Lap time feature in Stopwatch Project
  Public/stopwatch.html
  assets/Js/stopwatch.js
Labels: review-done, Level2, SSOC

#1025 Added form validation for Employee database project
  Public/employeeDatabase.html
  assets/Js/employeeDatabase.js
Labels: enhancement, review-done

#1040 feat: Mandatory Changes
  .github/ISSUE_TEMPLATE/Bug_Report.yml
  .github/ISSUE_TEMPLATE/Feature_Request.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: need-review
